---
swagger: "2.0"
info:
  x-ibm-name: "say-hello"
  title: "Say Hello"
  version: "1.0.0"
schemes:
- "https"
host: "$(catalog.host)"
basePath: "/say-hello"
produces:
- "application/json"
securityDefinitions:
  clientIdHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Id"
  clientSecretHeader:
    type: "apiKey"
    in: "header"
    name: "X-IBM-Client-Secret"
security:
- clientIdHeader: []
  clientSecretHeader: []
x-ibm-configuration:
  testable: true
  enforced: true
  cors:
    enabled: true
  assembly:
    execute:
    - set-variable:
        title: "set-variable hs256-key"
        actions:
        - set: "hs256-key"
          value: "{     \"kty\": \"oct\",     \"use\": \"sig\",     \"kid\": \"code2blog\"\
            ,     \"k\": \"rJq2TR03XXr96cMFd4r0x64ORV7v3-8-C6DF4j2EPSJQqO7LOmU9Jqd9_Jgdkj6dtcAq48W1RI2MDLKAa31DAX4MnW-ARGDi_A8HbEvPYxDGnfW0RPLDwws24JotlB0A0LoO-xGaCGiAEvk8JtEPmyzGU4qRwhJ-xuu4aHvs8dIAZWDskG34jvpPhydTN3DFye0b_78Ts27VARBRx2LvWrJnf3B_s_Hh_YJkyzGnXUnH8OXOFDvittXCofLbK3JsjKMwgOvIW67mLGcTjTMOgQVppfIE8Xnjsnt5D-khgnsdX2nmUz2L0cF9xAjk9NGrFz9vwG0d7mn2eYMXizM-5Q\"\
            ,     \"alg\": \"HS256\" }"
        version: "1.0.0"
        description: "set jwk"
    - jwt-generate:
        title: "jwt-generate"
        iss-claim: "request.headers.iss-claim"
        exp-claim: 3600
        version: "1.0.0"
        jti-claim: false
        sub-claim: ""
        aud-claim: "request.headers.aud-claim"
        jws-alg: "HS256"
        jwt: "generated-jwt"
        jws-jwk: "hs256-key"
        description: ""
    - map:
        title: "map"
        inputs:
          token:
            schema:
              type: "string"
            variable: "generated-jwt"
          key:
            schema:
              type: "string"
            variable: "hs256-key"
        outputs:
          output:
            schema:
              type: "object"
              properties:
                message:
                  type: "string"
                  name: "message"
                jwt:
                  type: "string"
                  name: "jwt"
                jwk:
                  type: "string"
                  name: "jwk"
            variable: "message.body"
            content: "application/json"
        actions:
        - set: "output.message"
          value: "'hello code2blog users'"
        - set: "output.jwk"
          from: "key"
        - set: "output.jwt"
          from: "token"
        version: "1.0.0"
        options: {}
  phase: "realized"
paths:
  /code2blog:
    get:
      responses:
        200:
          description: "200 OK"
      consumes:
      - "application/json"
      produces:
      - "application/json"
    parameters:
    - $ref: "#/parameters/iss-claim"
    - $ref: "#/parameters/aud-claim"
definitions: {}
tags: []
consumes:
- "application/json"
parameters:
  iss-claim:
    name: "iss-claim"
    type: "string"
    required: true
    in: "header"
    description: "iss-claim used in jwt generation"
  aud-claim:
    name: "aud-claim"
    type: "string"
    required: true
    in: "header"
    description: "aud-claim used in jwt generation"
